//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent_posrednika_table
    {
        public int id { get; set; }
        public System.DateTime datumunosa { get; set; }
        public int agent_id { get; set; }
        public string registarskibroj { get; set; }
        public bool UgovorAktivan { get; set; }
        public Nullable<System.DateTime> DatumRaskidaUgovora { get; set; }
        public Nullable<int> poslovni_subjekt_id { get; set; }
    
        public virtual Agent_table2 Agent_table2 { get; set; }
        public virtual Zapis_poslovnog_subjekta_table Zapis_poslovnog_subjekta_table { get; set; }
    }
}
