//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent_table2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent_table2()
        {
            this.Zapis_osobe_table = new HashSet<Zapis_osobe_table>();
            this.Agent_posrednika_table = new HashSet<Agent_posrednika_table>();
        }
    
        public int id { get; set; }
        public string registarskibroj { get; set; }
        public Nullable<System.DateTime> datumupisa { get; set; }
        public Nullable<System.DateTime> datumbrisanja { get; set; }
        public Nullable<System.DateTime> datumpolaganjaispita { get; set; }
        public string napomena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapis_osobe_table> Zapis_osobe_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agent_posrednika_table> Agent_posrednika_table { get; set; }
    }
}
