//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI20_037_DBEntities1 : DbContext
    {
        public PI20_037_DBEntities1()
            : base("name=PI20_037_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent_posrednika_table> Agent_posrednika_table { get; set; }
        public virtual DbSet<Korisnik_table> Korisnik_table { get; set; }
        public virtual DbSet<Naselje_table> Naselje_table { get; set; }
        public virtual DbSet<Strucna_sprema_table> Strucna_sprema_table { get; set; }
        public virtual DbSet<Tip_korisnika_table> Tip_korisnika_table { get; set; }
        public virtual DbSet<Vrsta_poslovnog_subjekta_table> Vrsta_poslovnog_subjekta_table { get; set; }
        public virtual DbSet<Zapis_osobe_table> Zapis_osobe_table { get; set; }
        public virtual DbSet<Zapis_poslovnog_subjekta_table> Zapis_poslovnog_subjekta_table { get; set; }
        public virtual DbSet<Zupanija_table> Zupanija_table { get; set; }
        public virtual DbSet<Agent_table2> Agent_table2 { get; set; }
    }
}
