//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik_table()
        {
            this.Zapis_osobe_table = new HashSet<Zapis_osobe_table>();
        }
    
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string korime { get; set; }
        public System.DateTime datumrodj { get; set; }
        public string lozinka { get; set; }
        public string kriptiranalozinka { get; set; }
        public int tip_korisnika_id { get; set; }
    
        public virtual Tip_korisnika_table Tip_korisnika_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapis_osobe_table> Zapis_osobe_table { get; set; }
    }
}
