//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vrsta_poslovnog_subjekta_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vrsta_poslovnog_subjekta_table()
        {
            this.Zapis_poslovnog_subjekta_table = new HashSet<Zapis_poslovnog_subjekta_table>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public string Oznaka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapis_poslovnog_subjekta_table> Zapis_poslovnog_subjekta_table { get; set; }
    }
}
