//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapis_osobe_table
    {
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datumrodj { get; set; }
        public string ulica { get; set; }
        public string jmbg { get; set; }
        public string oib { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public System.DateTime datumunosa { get; set; }
        public int korisnik_id { get; set; }
        public int strucna_sprema_id { get; set; }
        public int naselje_id { get; set; }
        public Nullable<int> agent_id { get; set; }
        public Nullable<System.DateTime> datumpolaganjaispita { get; set; }
    
        public virtual Korisnik_table Korisnik_table { get; set; }
        public virtual Naselje_table Naselje_table { get; set; }
        public virtual Strucna_sprema_table Strucna_sprema_table { get; set; }
        public virtual Agent_table2 Agent_table2 { get; set; }
    }
}
