//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapis_poslovnog_subjekta_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zapis_poslovnog_subjekta_table()
        {
            this.Agent_posrednika_table = new HashSet<Agent_posrednika_table>();
        }
    
        public int id { get; set; }
        public string matbroj { get; set; }
        public string naziv { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public System.DateTime datumunosa { get; set; }
        public string oib { get; set; }
        public int naselje_id { get; set; }
        public int vrsta_poslovnog_subjekta_id { get; set; }
    
        public virtual Naselje_table Naselje_table { get; set; }
        public virtual Vrsta_poslovnog_subjekta_table Vrsta_poslovnog_subjekta_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agent_posrednika_table> Agent_posrednika_table { get; set; }
    }
}
